apiVersion: v2
name: istio
description: Istio control
type: application
version: 1.0.0
appVersion: 1.30.2

dependencies:
  - name: istiod
    version: 1.30.2
    repository: https://istio-release.storage.googleapis.com/charts